

server:
  port: 8080
spring:
  application:
    name: antd
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meet?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
